### ISSUE TITLE
404 in urls person

### ISSUE THREAD

**Issue by manbago** [eci/mezzanine-people#1]
Hi,

i am using mezzanine-people for Mezzanine 3.1.10.
I add two person well but when i try to "View on site" get the error 404 page not found.

I added url(r'^people/', include('mezzanine_people.urls')),

I need add also? Thanks a lot.

![mezza2](https://cloud.githubusercontent.com/assets/1052369/8266971/35793b54-174b-11e5-89fe-a89e2fb443c9.png)
![mezza1](https://cloud.githubusercontent.com/assets/1052369/8266972/3587a52c-174b-11e5-994d-4093f5ba9470.png)

**Comment by eci** [comment]
Hi manbago,

I am not able to reproduce this issue testing with Mezzanine 3.1.10.

You will get a 404 if the person model does not have a status of "Published" but it appears from your screenshot that the person model you are attempting to view is published. Is it possible you changed the status from draft to published but had not yet saved the change before clicking the "View on site" link?

**Comment by manbago** [comment]
You are rigth!

I put  `<url(r'^people/', include('mezzanine_people.urls')),>`   after `<("^", include("mezzanine.urls")),>`.

The correct order is `<url(r'^people/', include('mezzanine_people.urls')),>`   before `<("^", include("mezzanine.urls")),>`.

Solve, Thanks.
